@baseUrl = http://localhost:5000

# @name signup
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
  "email": "tan03@gmail.com",
  "password": "123456"
}

###

# @name signin
POST {{baseUrl}}/auth/signin
Content-Type: application/json

{
  "email": "tan01@gmail.com",
  "password": "123456"
}

